version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - backend